# -*- coding: utf-8 -*-
"""practical3.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f54KeWO8NdITzU-6kQKHPl13KUGnbLSr
"""

#datatype
#numeric-int,float,complex

a=4
print(type(a))

b=7.8
print(type(b))

c=3+4j
print(type(c))

#character datatype-string,list,tuple

d='Jaipur'
print(type(d))

e='I am Good'
print(type(e))

f=[1,2,3.6,4,'Apple']    #square brackets
              #'comma'
              #We can add any data type in the list
              #Mutable-Can perform operations                                    #Ordered but mutable
              #Slow-dynamic(can be changed)
              #ordered collection

print(f)
print(type(f))

g=(1,2,3,4)               #Parentheses
                           #'comma
                           #Immutable(cannot be changed)                              #Ordered but immutable
                           #fast-static(cannot be changed)
                           #ordered
print(type(g))

f=[1,2,3.6,4,'Apple',2,3.8,9.8,10,'Guava',34,'Jaipur']                                       #append, insert, extend, pop, remove, index, count,sort,reverse, copy ,clear
print(f[-5])                                #indexing

print(f[0:5:2])
                                #slicing([start:end+1:[stepsize]])
print(f[4:11:3])                         #'Apple,9.8,'Guava'

print(f[2:6:2])

print(f[-1:-5:1])

print(f[-1:-4:-2])

print(f[-3:-8:-2])             #Guava,2,[guava,9.8,2]

print(f[-2:-8:2])               #34,2,[]

print(f[-4:-1:-2])              #10,34,[]

print(f[-4:-1:1])                #10,34,[10,guava,34]

print(f[-2:-6:-3])                #34,9.8,[34,9.8]

print(f[1:8:-2])                 #2,9.8,[]